language: python
matrix:
  include:
#  - python: "3.4"
#    env: TEST_SUITE=test/suite_3_4.py
  - python: "3.5"
    env: TEST_SUITE=test/*.py
#  - python: "3.6"
#    env: TEST_SUITE=test/suite_3_6.py
# command to install dependencies
addons: # get google-chrome-stable
  chrome: stable
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
install:
  - pip install -r requirements.txt
  - pip install Flask-SQLAlchemy
  - pip install selenium
# command to run test
script:
  - whereis google-chrome-stable
  - whereis chromedriver
  - pytest $TEST_SUITE # or py.test for Python versions 3.5 and below