language: python
matrix:
  include:
  - python: "3.5"
    env: TEST_SUITE=test/*_test.py
# command to install dependencies
addons: # get google-chrome-stable
  chrome: stable
install:
  - pip install -r requirements.txt
  - pip install Flask-SQLAlchemy
  - pip install selenium
  - pip install chromedriver
# command to run test
script:
  - pytest $TEST_SUITE # or py.test for Python versions 3.5 and below